### ISSUE TITLE
Add feature to allow animation effects / integration with sequencer or Automated Animations

### ISSUE THREAD

**Issue by Tatonker** [arbron/fvtt-summoner#21]
**Is your feature request related to a problem? Please describe.**
Currently summoning works very well, but for something like the 'Summon Wildfire Spirit' it would be fantastic to add some visual flair via adding some animations, for example from the JB2A module of animated effects. Prior to finding your module I had a complex macro for both summoning and using sequencer to generate the visual effect of the token being summoned in a burst of flame.

**Describe the solution you'd like**
Either adding some element of animation configuration within the module itself, or build some hooks (or whatever, sorry not a coder so probably not using the right terminology) to allow Automated Animations to pick up on the summoning data being used eg. location of summons etc... I attempted to create something in A-A but as it does not know where the token is being summoned to, the best that could be achieved was creating an effect on the summoner themselves.

**Describe alternatives you've considered**

**Additional context**

**Comment by Verthiss** [comment]
I agree, something similar to TheRipper93's implementation of summoning animations in Automatic Evocations module would be awesome. I vastly prefer your mod in general because it's much more user friendly, but summoning animation would take it to the next level :)
