### ISSUE TITLE
[BUG] Potential compatibility issue with WIRE

### ISSUE THREAD

**Issue by YenBenGrey** [arbron/fvtt-summoner#23]
**Describe the bug**
I have followed the instructions to try and create Summon Aberration and nothing is being summoned. 

**Environment:**
 - Foundry Core Version: V10 291
 - Module Version 1.0.6
 - Host: Molten
 - OS & Browser Mac Ventura and Chrome

**Additional context**
The example looks like an item whereas I am trying to do this with a spell

**Comment by arbron** [comment]
This is because WIRE doesn't call the default 5e hooks. This is being fixed on WIRE's end.
