### ISSUE TITLE
[FEATURE] List of summoner attributes we can use

### ISSUE THREAD

**Issue by Nedrapter** [arbron/fvtt-summoner#33]
Not exactly a feature but, other than the @Summoner.item.level used in the example, what other variables can we use? A list with those would be very helpful.

**Comment by arbron** [comment]
The `@summoner` data is just the summoner’s roll data, so anything you could normally access through formulas is accesible there

**Comment by Nedrapter** [comment]
When I use @summoner.prof I get the above error, which mentions the system and 2 other modules but only happens with the "summoner" variables
![image](https://user-images.githubusercontent.com/74311190/233211782-3286eb7f-a139-409a-949a-85ea127e239f.png)

**Comment by Nedrapter** [comment]
Which is why I thought there was a separate list of variables for it.

**Comment by arbron** [comment]
What version of summoner are you using? Because that look alike you are hitting #18 which should have been resolved with `1.0`. Maybe there is some interaction with another module.

**Comment by Nedrapter** [comment]
> What version of summoner are you using? Because that look alike you are hitting #18 which should have been resolved with `1.0`. Maybe there is some interaction with another module.

I'm using 1.0.5 version currently.

**Comment by Mazarkus** [comment]
I would second that having a list of what the available @summoner properties are would be very useful to have.  For example if I wanted to build a Steel Defender for an Artificer, I don't see any examples of how to extract the summoner's intelligence bonus.  Is it @summoner.int? @summoner.item.int?  @summoner.intelligence?  I'm having to try to guess what the list of available values is

**Comment by Seamonster73** [comment]
> I would second that having a list of what the available @Summoner properties are would be very useful to have. For example if I wanted to build a Steel Defender for an Artificer, I don't see any examples of how to extract the summoner's intelligence bonus. Is it @summoner.int? @summoner.item.int? @summoner.intelligence? I'm having to try to guess what the list of available values is

I'd third this. 

Or alternatively, rather than a list it would be extremely helpful to have a command or commands that could be run in the console that would show all of the currently available variables that might be relevant in certain common situations. E.g. how to show the roll data of the summoning actor/item/feature.

Presently it's a bit of a head-scratcher trying to work out what might work for the summoned item you're trying to set up.
