### ISSUE TITLE
[BUG] Armour causes issues in dnd5e when summoning a spiritual weapon

### ISSUE THREAD

**Issue by maxobremer** [arbron/fvtt-summoner#36]
**Describe the bug**
After a lot of testing i found that (in dnd5e) having studded leather armour or a shield or both equipped causes issues. if you have either equipped and try to summon a creature that uses for example your proficiency or to hit bonus, it will summon, but not with any bonusses or information that could be derived from the summoner. 

**To Reproduce**
Steps to reproduce the behaviour:
1. make a new world and enable just this module and warp gate
2. make a summoning creature like a spiritual weapon and a character with a spell or feature that summons the summon
3. give the summoner a shield or studded leather armour and equip it
4. try to summon the weapon or other summon
5. get the following error in the f12 menu
![image](https://github.com/arbron/fvtt-summoner/assets/86924581/4633bb3d-f7ff-4d12-a1ad-cb85435647b8)

**Expected behavior**
To work as intended even if your cleric is wearing armour.

**Screenshots**
see above
![image](https://github.com/arbron/fvtt-summoner/assets/86924581/27521f43-37b5-4783-b244-d2a5cacaa6c9)
wrong behaviour, summon also lacks the dismiss button.

![image](https://github.com/arbron/fvtt-summoner/assets/86924581/b6b2fcbe-f83b-4764-9400-97cd7baa3082)
Correct behaviour when no armour is equipped

**Environment:**
 - Foundry Core Version: V11 build 302
 - DnD5e build: 2.2.1
 - Module Version 1.1.3
 - Warp Gate Version: 1.17.2
 - Host: Self Hosted
 - OS & Browser the Foundry program itself i guess]

**Additional context**

**Comment by kaelad02** [comment]
+1 can confirm. Odd that unequipping any armor or shields makes it work again.

**Comment by YenBenGrey** [comment]
+2 only in v11, works perfectly in v10. 

Also can confirm, works when the Cleric unequips their armour.

**Comment by StephenDiamond** [comment]
This appears to be caused by the mergeObject call within the actor.update call in warpgate. When you pass in the rollData to the arbron-summoner flag it includes the attributes of the summoner - including their ac calculation and that includes "equippedArmor" which appears to be read-only. So when it attempts to merge the object, this causes an error and doesn't apply the summoner calculation changes.
