### ISSUE TITLE
Compatibility with dnd5e 3.x

### ISSUE THREAD

**Issue by nschoenwald** [arbron/fvtt-summoner#48]
The module is currently not compatible with the new dnd5e 3.x system update. Will it be updated? That would be awesome, this module really makes all summoning features so much easier to use.

**Comment by arbron** [comment]
It should be, I tested it and updated the compatibility version with the latest release. Is there something not working for you?

**Comment by nschoenwald** [comment]
The one issue I just encountered in my session is that the proficiency bonus was not correctly transferred from summoner to the summon. This happened in the damage formula, to be exact.

**Comment by arbron** [comment]
Can you show me the roll chat message, the summons configuration on the summoned actor, the changes tab on the active effect that sets the proficiency on the summoned actor, and the bottom of the details tab of the attack on the summoned actor?

**Comment by nschoenwald** [comment]
I was using `@summoner.prof`, which ceased to work with the dnd5e 3.x update. I changed it to `@prof` now, since the prof matches the summoner's prof anyways. It works that way.
