### ISSUE TITLE
[FEATURE] Support for dice formula in number or summons

### ISSUE THREAD

**Issue by Ikabodo** [arbron/fvtt-summoner#53]
**Is your feature request related to a problem? Please describe.**
Several magical items in 5e summons a random number of, or rather, based on a dice formula. 

**Describe the solution you'd like**
Add support for dice formulas in the summons box.
![image](https://github.com/arbron/fvtt-summoner/assets/7766890/431bd2c0-5c1f-41c9-95a0-b3029ac3fe48)

**Comment by Kharmans** [comment]
Adding for that: not just dices, but for @prof, for example. But I think make it accept formulas already would cover that.
