### ISSUE TITLE
Question: Continued 5e support?

### ISSUE THREAD

**Issue by nsm91** [arbron/fvtt-summoner#55]
Hello, I know you are on the dev team for the 5e system and it recently added summon support. But your mod does things that 5e still can't, and running both of them at once works but generates errors. Will there be patches generated or will all of the functionality for this eventually be in 5e.

One concrete example, this package has dialogues at the bottom where you can pass in any actor attribute keys based on the summoner, but in 5e there are no free form windows last I checked. But 5e doesn't also have every single feature editable, this this package has way more functionality in that way. I can provide screenshots if it's not clear.

**Comment by arbron** [comment]
The module will not continue development due to the system feature and losing Warp Gate in the V12 transition. If there are features you still require, feel free to file issues on the 5e repo with your use case so we can implement them over there.
