### ISSUE TITLE
Error during summoning "Cannot read properties of null (reading 'summon')"

### ISSUE THREAD

**Issue by Stormthirst** [arbron/fvtt-summoner#57]
**Describe the bug**
Whilst using the Summon feature I get the error:
"Cannot read properties of null (reading 'summon')"

**To Reproduce**
Created feature for "Summon Wildfire Spirit"
Click to place the Wildfire spirit - I notice there are two "summon" check boxes. Not sure if that's normal
The damage template works as intended, but it doesn't place the token

**Expected behavior**
Should place token, but doesn't

**Environment:**
 - Foundry Core Version: 11.315
 - Module Version: 1.1.6
 - Host: Self hosted on a Ubuntu Linux PC
 - OS & Browser: Windows 11, Chrome 125.0.6422.142

**Comment by arbron** [comment]
Summoning has been integrated into the DnD5e system and it conflicts with the module implementation. I recommend uninstalling the module and switching to the system's summoning features.
