### ISSUE TITLE
[FEATURE] Compatability with tidySheet5e

### ISSUE THREAD

**Issue by Ikabodo** [arbron/fvtt-summoner#8]
**Is your feature request related to a problem? Please describe.**
If you use tidySheet5e you have to enable to default sheet to find summon settings. 
![image](https://user-images.githubusercontent.com/7766890/189351961-a7ed0c3b-c3e8-4ff5-8648-c55f6aa58460.png)
![image](https://user-images.githubusercontent.com/7766890/189351991-0ee5bf22-98de-4dc9-8c08-0dfab451fa66.png)

**Describe the solution you'd like**
It would be nice if the summoner settings was reachable directly on the tidy sheet.

**Describe alternatives you've considered**
The current workaround works ofcourse, but it's a bit clunky.

**Comment by arbron** [comment]
@Ikabodo The `"Summon Configuration"` window is always available by going into the `"Special Traits"` menu regardless of what custom sheet you use.

I will look into adding it to the top level of TidySheet.

**Comment by Ikabodo** [comment]
Thank you, and sorry for my miss. I honestly think it fits grat where you put it under special traits, and if anything the use macro part should be where yours is.

Thanks for the answer!
