### ISSUE TITLE
[FEATURE] Dynamic damage on attacks

### ISSUE THREAD

**Issue by Ikabodo** [arbron/fvtt-summoner#9]
**Is your feature request related to a problem? Please describe.**
A lot of summons increases the damage to attacks when the spell is upcast. Currently it's not possible to increase the damage on attacks on an actor sheet through the summoning. (to my knowledge, but it might be possible with attributes?) 

**Describe the solution you'd like**
An option to add damage to certain attacks based on level.

**Comment by arbron** [comment]
The summoning spell's roll data is made available to the summoned actor, so you can add `@summoner.item.level` into a damage formula to get the spell level that was used for the summoning. Check out the [readme](https://github.com/arbron/fvtt-summoner/blob/main/readme.md) for more info.
